

export const USER_LOADED = 'USER_LOADED';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';


export const MOVIES_LOAD_SUCCESS = 'MOVIES_LOAD_SUCCESS';
export const MOVIES_LOAD_FAIL = 'MOVIES_LOAD_FAIL';

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';
export const LOAD_FAVOURITES_FAIL = 'LOAD_FAVOURITES_FAIL';
