

export const USER_LOADED = 'USER_LOADED';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGOUT = 'LOGOUT';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';


export const MOVIES_LOAD_SUCCESS = 'MOVIES_LOAD_SUCCESS';
export const MOVIES_LOAD_FAIL = 'MOVIES_LOAD_FAIL';

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';
export const LOAD_FAVOURITES_FAIL = 'LOAD_FAVOURITES_FAIL';

export const MOVIE_DELETED = 'MOVIE_DELETED';
export const DELETE_MOVIE_FAIL = 'DELETE_MOVIE_FAIL';

export const SET_SEARCH_STR = 'SET_SEARCH_STR';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const PAGINATE_SUCCESS = 'PAGINATE_SUCCESS';
export const PAGINATE_FAIL = 'PAGINATE_FAIL';
export const UPDATE_PAGE = 'UPDATE_PAGE';
